'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { ArrowRight, BarChart3, BrainCircuit, Building2, Camera, Check, ChevronRight, Eye, EyeOff, Gauge, Menu, ParkingCircle, ShieldCheck, Sparkles, X } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Logo } from './shell'

export function LandingPage() {
  const [menu, setMenu] = useState(false)
  return <div className="min-h-screen overflow-hidden bg-background">
    <header className="fixed inset-x-0 top-0 z-40 border-b bg-background/85 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5"><Logo /><nav className="hidden items-center gap-8 text-sm font-medium md:flex"><a href="#platform">Platform</a><a href="#solutions">Solutions</a><a href="#insights">Insights</a></nav><div className="hidden items-center gap-3 md:flex"><Link className="button-secondary" href="/login">Sign in</Link><Link className="button-primary" href="/admin">Explore dashboard <ArrowRight /></Link></div><button className="icon-button md:hidden" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X /> : <Menu />}</button></div>{menu && <nav className="flex flex-col gap-2 border-t bg-background p-4 md:hidden"><a className="nav-item" href="#platform">Platform</a><a className="nav-item" href="#solutions">Solutions</a><Link className="button-primary justify-center" href="/login">Sign in</Link></nav>}</header>
    <main>
      <section className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-12 px-5 pb-20 pt-32 lg:grid-cols-[1.05fr_.95fr]">
        <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border bg-muted/60 px-3 py-1.5 text-xs font-semibold text-primary"><Sparkles className="size-3.5" />AI-powered parking operations</div><h1 className="max-w-3xl text-balance text-5xl font-bold leading-[1.04] tracking-[-.045em] md:text-7xl">Every parking space, intelligently managed.</h1><p className="mt-6 max-w-xl text-pretty text-lg leading-relaxed text-muted-foreground">SmartPark AI unifies access, occupancy, residents, and predictive insights in one precise operating system for modern properties.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="button-primary button-lg" href="/admin">Open live dashboard <ArrowRight /></Link><Link className="button-secondary button-lg" href="/resident">View resident app</Link></div><div className="mt-10 flex flex-wrap gap-6 text-sm text-muted-foreground"><span className="flex items-center gap-2"><Check className="size-4 text-success" />No hardware lock-in</span><span className="flex items-center gap-2"><Check className="size-4 text-success" />Real-time deployment</span></div></div>
        <div className="relative"><div className="hero-console"><div className="flex items-center justify-between border-b p-4"><div><p className="text-xs font-medium text-muted-foreground">LIVE OCCUPANCY</p><p className="mt-1 text-xl font-semibold">North Tower · Level A</p></div><span className="status status-success"><span className="size-1.5 rounded-full bg-current" />Live</span></div><div className="grid grid-cols-3 gap-3 p-4 sm:grid-cols-4">{Array.from({ length: 20 }, (_, i) => <div key={i} className={`aspect-[1.25] rounded-lg border p-2 ${i % 5 < 3 ? 'border-primary/20 bg-primary/10' : i % 5 === 3 ? 'border-warning/30 bg-warning/10' : 'border-success/25 bg-success/10'}`}><span className="font-mono text-[10px] text-muted-foreground">A-{String(i + 1).padStart(2, '0')}</span>{i % 5 < 3 && <div className="mt-2 h-4 rounded bg-primary/50" />}</div>)}</div><div className="grid grid-cols-3 border-t"><Metric value="68%" label="Occupied" /><Metric value="127" label="Available" /><Metric value="4.2m" label="Avg. entry" /></div></div><div className="absolute -bottom-5 -left-5 hidden rounded-2xl border bg-background p-4 shadow-xl sm:block"><div className="flex items-center gap-3"><span className="stat-icon stat-primary"><BrainCircuit /></span><div><p className="text-xs text-muted-foreground">AI forecast</p><p className="font-semibold">Peak in 42 minutes</p></div></div></div></div>
      </section>
      <section id="platform" className="border-y bg-muted/30"><div className="mx-auto max-w-7xl px-5 py-24"><p className="section-kicker">One operational layer</p><h2 className="section-title">Built to see, decide, and act.</h2><div className="mt-12 grid gap-4 md:grid-cols-3"><Feature icon={Gauge} title="Live occupancy" text="A real-time view of every space, vehicle, floor, and access event across your portfolio." /><Feature icon={BrainCircuit} title="Predictive intelligence" text="Forecast demand, identify anomalies, and optimize allocations before congestion occurs." /><Feature icon={ShieldCheck} title="Automated access" text="Manage permits, guests, approvals, and enforcement with auditable, policy-aware flows." /></div></div></section>
      <section id="solutions" className="mx-auto grid max-w-7xl gap-16 px-5 py-24 lg:grid-cols-2 lg:items-center"><div><p className="section-kicker">Clarity at scale</p><h2 className="section-title">From one garage to an entire portfolio.</h2><p className="mt-5 max-w-xl leading-relaxed text-muted-foreground">Give operators the control room they need and residents the simple, seamless experience they expect.</p><ul className="mt-8 flex flex-col gap-4">{['Computer vision-ready occupancy', 'Resident and guest self-service', 'Automated exceptions and approvals', 'Portfolio-wide analytics'].map(x => <li key={x} className="flex items-center gap-3 font-medium"><span className="grid size-6 place-items-center rounded-full bg-primary/10 text-primary"><Check className="size-3.5" /></span>{x}</li>)}</ul></div><div className="panel grid gap-3 p-4 sm:grid-cols-2"><FeatureMini icon={Camera} label="Vision systems" value="24 online" /><FeatureMini icon={Building2} label="Properties" value="12 connected" /><FeatureMini icon={BarChart3} label="Efficiency" value="+18.4%" /><FeatureMini icon={ParkingCircle} label="Managed spaces" value="4,820" /></div></section>
      <section id="insights" className="mx-5 mb-8 rounded-3xl bg-primary px-6 py-16 text-primary-foreground md:px-12"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-sm font-semibold text-primary-foreground/70">READY TO MOVE</p><h2 className="mt-3 max-w-2xl text-balance text-3xl font-bold md:text-5xl">Make parking your smartest property asset.</h2></div><Link href="/login" className="inline-flex h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-background px-6 font-semibold text-foreground">Start exploring <ChevronRight /></Link></div></section>
    </main><footer className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-5 py-10 text-sm text-muted-foreground md:flex-row"><Logo /><p>© 2026 SmartPark AI. Intelligent parking operations.</p></footer>
  </div>
}

function Metric({ value, label }: { value: string; label: string }) { return <div className="p-4"><p className="text-xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div> }
function Feature({ icon: Icon, title, text }: { icon: typeof Gauge; title: string; text: string }) { return <article className="panel p-6"><span className="stat-icon stat-primary"><Icon /></span><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p></article> }
function FeatureMini({ icon: Icon, label, value }: { icon: typeof Gauge; label: string; value: string }) { return <article className="rounded-xl border bg-background p-5"><Icon className="size-5 text-primary" /><p className="mt-8 text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></article> }

export function LoginPage() {
  const router = useRouter(); const [role, setRole] = useState<'admin' | 'resident'>('admin'); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false)
  function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setTimeout(() => router.push(role === 'admin' ? '/admin' : '/resident'), 450) }
  return <main className="grid min-h-screen lg:grid-cols-2"><section className="hidden flex-col justify-between bg-primary p-12 text-primary-foreground lg:flex"><Logo /><div><div className="mb-8 grid size-16 place-items-center rounded-2xl bg-primary-foreground/12"><BrainCircuit className="size-8" /></div><h1 className="max-w-xl text-balance text-5xl font-bold tracking-tight">Parking intelligence that moves with you.</h1><p className="mt-5 max-w-lg text-lg leading-relaxed text-primary-foreground/70">One secure workspace for operators and residents to manage every parking moment.</p></div><p className="text-sm text-primary-foreground/60">Trusted by modern residential communities.</p></section><section className="flex items-center justify-center p-5 md:p-10"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><Logo /></div><p className="section-kicker">Welcome back</p><h1 className="mt-2 text-3xl font-bold">Sign in to SmartPark</h1><p className="mt-2 text-sm text-muted-foreground">Use the demo credentials to explore your workspace.</p><div className="mt-8 grid grid-cols-2 rounded-xl bg-muted p-1"><button className={`role-tab ${role === 'admin' ? 'role-tab-active' : ''}`} onClick={() => setRole('admin')}>Administrator</button><button className={`role-tab ${role === 'resident' ? 'role-tab-active' : ''}`} onClick={() => setRole('resident')}>Resident</button></div><form className="mt-6 flex flex-col gap-5" onSubmit={submit}><label className="field"><span>Email address</span><input type="email" defaultValue={role === 'admin' ? 'admin@smartpark.ai' : 'olivia@example.com'} required /></label><label className="field"><span>Password</span><span className="relative"><input type={show ? 'text' : 'password'} defaultValue="smartpark2026" required className="w-full pr-11" /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground" aria-label="Toggle password visibility">{show ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></span></label><div className="flex items-center justify-between text-sm"><label className="flex items-center gap-2"><input type="checkbox" defaultChecked />Remember me</label><button type="button" className="font-medium text-primary">Forgot password?</button></div><button className="button-primary h-12 justify-center" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'} <ArrowRight /></button></form><p className="mt-6 rounded-xl border bg-muted/40 p-3 text-center text-xs text-muted-foreground">Demo mode — any valid email and password will work.</p></div></section></main>
}
