'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { ArrowRight, BarChart3, BrainCircuit, Building2, Camera, Check, ChevronRight, Eye, EyeOff, Gauge, Menu, ParkingCircle, Radio, ShieldCheck, Sparkles, Bot, X } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Logo } from './shell'

export function LandingPage() {
  const [menu, setMenu] = useState(false)
  return (
    <div className="min-h-screen overflow-hidden bg-background">
      <header className="sticky top-0 z-40 border-b bg-card/85 px-4 backdrop-blur-md md:px-8">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between"><div className="flex items-center gap-8"><Logo /><nav className="hidden items-center gap-5 text-xs text-muted-foreground md:flex"><a href="#features" className="hover:text-primary">Features</a><a href="#assistant" className="hover:text-primary">AI Assistant</a><a href="#how-it-works" className="hover:text-primary">About</a><a href="#contact" className="hover:text-primary">Contact</a></nav></div><div className="flex items-center gap-2"><Link className="hidden rounded-lg px-3 py-2 text-xs font-medium text-muted-foreground hover:bg-muted sm:inline-flex" href="/login">Login</Link><Link className="button-primary h-9 rounded-lg px-4 text-xs" href="/login">Get Started</Link><button className="icon-button md:hidden" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X /> : <Menu />}</button></div></div>
        {menu && <nav className="flex flex-col gap-2 border-t py-3 md:hidden"><a className="nav-item" href="#features">Features</a><a className="nav-item" href="#assistant">AI Assistant</a><Link className="nav-item" href="/login">Login</Link></nav>}
      </header>
      <main className="mx-auto max-w-7xl px-4 md:px-8">
        <section className="relative py-16 lg:py-24"><div className="relative z-10 max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 text-xs font-medium text-primary"><Sparkles className="size-3.5" />Next-Gen Urban Mobility</div><h1 className="max-w-3xl text-balance text-5xl font-bold leading-tight tracking-[-.04em] md:text-7xl">Smart Parking Management <span className="bg-gradient-to-r from-primary to-primary bg-clip-text text-transparent">Powered by AI</span></h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-muted-foreground md:text-lg">Optimize city space and maximize revenue with enterprise-grade AI. Real-time monitoring, predictive analytics, and resident-first workflows in one unified dashboard.</p><div className="mt-10 flex flex-wrap gap-4"><Link className="button-primary button-lg rounded-xl" href="/login">Start Free Trial <ArrowRight /></Link><a className="button-secondary button-lg rounded-xl" href="#features">Watch Demo</a></div></div><DashboardPreview /></section>
        <section className="mb-20 grid grid-cols-2 gap-8 border-y py-12 md:grid-cols-4"><Metric value="98%" label="Accuracy Rate" /><Metric value="30m+" label="Transactions" /><Metric value="15%" label="Revenue Growth" /><Metric value="24/7" label="AI Monitoring" /></section>
        <section id="features" className="py-16"><div className="mb-12"><h2 className="text-3xl font-semibold tracking-tight">Enterprise Intelligence Features</h2><p className="mt-3 max-w-xl text-sm leading-relaxed text-muted-foreground">Every tool you need to manage modern parking infrastructure, powered by intelligent automation.</p></div><div className="grid gap-6 md:grid-cols-12 md:grid-rows-2"><article id="assistant" className="panel relative overflow-hidden p-8 md:col-span-8"><Sparkles className="mb-5 size-8 text-primary" /><h3 className="text-lg font-semibold">Predictive AI Assistant</h3><p className="mt-2 max-w-md text-sm leading-relaxed text-muted-foreground">Anticipate demand surges before they happen and receive actionable insights to optimize flow and resident experience.</p><div className="mt-8 rounded-xl border bg-muted/50 p-4 text-xs text-muted-foreground">“Parking demand in Sector 4 is projected to increase by 22% in the next hour.”</div></article><Feature icon={Radio} title="Real-time Availability" text="Sub-second tracking of every individual parking space across your entire network." /><Feature icon={Bot} title="Smart Automation" text="Automate approvals, access workflows, and exceptions without manual intervention." /><article className="panel flex items-center gap-6 p-8 md:col-span-8"><div className="flex-1"><BarChart3 className="mb-5 size-7 text-primary" /><h3 className="text-lg font-semibold">Advanced Fleet Analytics</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Detailed heatmaps, utilization trends, and operational forecasting at your fingertips.</p></div><div className="hidden h-28 w-40 items-end gap-2 rounded-xl bg-muted p-4 sm:flex">{[40,60,45,85,55,70].map((height, index) => <span key={index} className="flex-1 rounded-t bg-primary/60" style={{ height: `${height}%` }} />)}</div></article></div></section>
        <section id="how-it-works" className="my-24 rounded-3xl border bg-card p-8 md:p-12"><h2 className="text-center text-2xl font-semibold md:text-3xl">Simple Integration. Powerful Results.</h2><div className="relative mt-12 grid gap-10 md:grid-cols-3 md:gap-12"><div className="absolute left-1/4 right-1/4 top-5 hidden h-px bg-border md:block" />{[['1','Connect Sensors','Connect existing parking data sources through a secure gateway.'],['2','AI Processing','Our intelligence layer turns occupancy and activity into clear decisions.'],['3','Go Live','Start optimizing your parking assets with a focused operating workspace.']].map(([number,title,text]) => <div key={number} className="relative z-10 text-center"><div className="mx-auto grid size-10 place-items-center rounded-full bg-primary text-sm font-semibold text-primary-foreground">{number}</div><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{text}</p></div>)}</div></section>
        <section id="contact" className="py-24 text-center"><div className="mx-auto max-w-2xl"><h2 className="text-balance text-3xl font-bold tracking-tight md:text-5xl">Ready to revolutionize your parking infrastructure?</h2><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link className="button-primary button-lg rounded-xl" href="/login">Request Enterprise Demo</Link><a className="button-secondary button-lg rounded-xl" href="mailto:hello@smartpark.ai">Contact Sales</a></div><p className="mt-8 text-xs text-muted-foreground">Trusted by 50+ modern communities worldwide</p></div></section>
      </main>
      <footer className="border-t bg-card px-4 py-12 md:px-8"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-4"><div><Logo /><p className="mt-4 max-w-xs text-xs leading-relaxed text-muted-foreground">Redefining urban mobility through intelligent parking operations.</p></div>{[['Product','Features','Pricing','Case Studies','API Docs'],['Company','About Us','Careers','Press Kit','Sustainability'],['Legal','Privacy Policy','Terms of Service','Cookie Policy']].map(([title,...items]) => <div key={title}><h3 className="text-xs font-semibold uppercase tracking-wider">{title}</h3><ul className="mt-5 flex flex-col gap-3 text-xs text-muted-foreground">{items.map((item) => <li key={item}><a href="#" className="hover:text-primary">{item}</a></li>)}</ul></div>)}</div><div className="mx-auto mt-10 max-w-7xl border-t pt-5 text-[10px] text-muted-foreground">© 2026 SmartPark AI. All rights reserved.</div></footer>
    </div>
  )
}

function DashboardPreview() {
  const bars = [40, 60, 45, 85, 55, 70, 50]
  return <div className="group relative mt-14"><div className="hero-console aspect-[16/9] !transform-none"><div className="flex h-full"><aside className="hidden w-14 flex-col items-center gap-7 border-r bg-muted/50 py-6 sm:flex"><LayoutIcon /><MapIcon /><CarIcon /><ChartIcon /></aside><div className="relative flex-1 overflow-hidden bg-card p-5 md:p-8"><div className="absolute inset-0 opacity-30" style={{ backgroundImage: 'linear-gradient(135deg, transparent 49%, var(--border) 50%, transparent 51%), linear-gradient(45deg, transparent 49%, var(--border) 50%, transparent 51%)', backgroundSize: '80px 80px' }} /><div className="relative flex items-start justify-between"><div><h3 className="text-lg font-semibold">District Overview</h3><p className="text-xs text-muted-foreground">Live occupancy data · SOMA District</p></div><div className="rounded-xl border bg-card p-3 shadow-sm"><p className="text-[10px] text-muted-foreground">Available</p><p className="text-lg font-semibold text-success">1,240</p></div></div><div className="relative mt-auto flex h-32 items-end gap-3 pt-12">{bars.map((height, index) => <span key={index} className="flex-1 rounded-t bg-primary/45" style={{ height: `${height}%` }} />)}</div><div className="absolute bottom-4 right-4 w-56 rounded-xl border bg-card/90 p-3 shadow-lg backdrop-blur"><div className="flex items-center gap-2 text-[10px] text-muted-foreground"><span className="size-2 rounded-full bg-success" />AI Assistant · Thinking</div><p className="mt-2 text-[10px] leading-relaxed">Parking demand in Sector 4 is projected to increase by 22% in the next hour.</p><button className="mt-2 rounded bg-primary px-2 py-1 text-[9px] font-semibold text-primary-foreground">Apply Pricing</button></div></div></div></div></div>
}
function LayoutIcon() { return <Gauge className="size-4 text-primary" /> }
function MapIcon() { return <Building2 className="size-4 text-muted-foreground" /> }
function CarIcon() { return <ParkingCircle className="size-4 text-muted-foreground" /> }
function ChartIcon() { return <BarChart3 className="size-4 text-muted-foreground" /> }


function Metric({ value, label }: { value: string; label: string }) { return <div className="p-4"><p className="text-xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div> }
function Feature({ icon: Icon, title, text }: { icon: typeof Gauge; title: string; text: string }) { return <article className="panel p-6"><span className="stat-icon stat-primary"><Icon /></span><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p></article> }
function FeatureMini({ icon: Icon, label, value }: { icon: typeof Gauge; label: string; value: string }) { return <article className="rounded-xl border bg-background p-5"><Icon className="size-5 text-primary" /><p className="mt-8 text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></article> }

export function LoginPage() {
  const router = useRouter(); const [role, setRole] = useState<'admin' | 'resident'>('admin'); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false)
  function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setTimeout(() => router.push(role === 'admin' ? '/admin' : '/resident'), 450) }
  return <main className="grid min-h-screen lg:grid-cols-2"><section className="hidden flex-col justify-between bg-primary p-12 text-primary-foreground lg:flex"><Logo /><div><div className="mb-8 grid size-16 place-items-center rounded-2xl bg-primary-foreground/12"><BrainCircuit className="size-8" /></div><h1 className="max-w-xl text-balance text-5xl font-bold tracking-tight">Parking intelligence that moves with you.</h1><p className="mt-5 max-w-lg text-lg leading-relaxed text-primary-foreground/70">One secure workspace for operators and residents to manage every parking moment.</p></div><p className="text-sm text-primary-foreground/60">Trusted by modern residential communities.</p></section><section className="flex items-center justify-center p-5 md:p-10"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><Logo /></div><p className="section-kicker">Welcome back</p><h1 className="mt-2 text-3xl font-bold">Sign in to SmartPark</h1><p className="mt-2 text-sm text-muted-foreground">Use the demo credentials to explore your workspace.</p><div className="mt-8 grid grid-cols-2 rounded-xl bg-muted p-1"><button className={`role-tab ${role === 'admin' ? 'role-tab-active' : ''}`} onClick={() => setRole('admin')}>Administrator</button><button className={`role-tab ${role === 'resident' ? 'role-tab-active' : ''}`} onClick={() => setRole('resident')}>Resident</button></div><form className="mt-6 flex flex-col gap-5" onSubmit={submit}><label className="field"><span>Email address</span><input type="email" defaultValue={role === 'admin' ? 'admin@smartpark.ai' : 'olivia@example.com'} required /></label><label className="field"><span>Password</span><span className="relative"><input type={show ? 'text' : 'password'} defaultValue="smartpark2026" required className="w-full pr-11" /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground" aria-label="Toggle password visibility">{show ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></span></label><div className="flex items-center justify-between text-sm"><label className="flex items-center gap-2"><input type="checkbox" defaultChecked />Remember me</label><button type="button" className="font-medium text-primary">Forgot password?</button></div><button className="button-primary h-12 justify-center" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'} <ArrowRight /></button></form><p className="mt-6 rounded-xl border bg-muted/40 p-3 text-center text-xs text-muted-foreground">Demo mode — any valid email and password will work.</p></div></section></main>
}
