'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { CalendarClock, CarFront, Check, ChevronLeft, Clock3, Copy, Edit3, KeyRound, MapPin, MoreHorizontal, Plus, QrCode, Share2, ShieldCheck, Trash2, UserPlus, Users, X } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Modal, PageHeader, ResidentShell, Status } from './shell'

export function ResidentDashboard() {
  return <ResidentShell><PageHeader eyebrow="Resident portal" title="Welcome home, Olivia" description="Manage your vehicles, parking space, and guest access from one place." /><section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><article className="overflow-hidden rounded-2xl bg-primary p-6 text-primary-foreground shadow-lg"><div className="flex items-start justify-between"><div><p className="text-sm text-primary-foreground/70">YOUR ASSIGNED SPACE</p><p className="mt-3 font-mono text-4xl font-bold">A-024</p><p className="mt-2 flex items-center gap-2 text-sm"><MapPin className="size-4" />North Tower · Level A</p></div><span className="grid size-12 place-items-center rounded-2xl bg-primary-foreground/12"><CarFront /></span></div><div className="mt-12 flex items-center justify-between rounded-xl bg-primary-foreground/10 p-4"><div><p className="text-xs text-primary-foreground/65">CURRENT STATUS</p><p className="mt-1 font-semibold">Vehicle parked since 8:42 AM</p></div><Status tone="success">Active</Status></div></article><article className="panel p-5"><p className="section-kicker">This month</p><div className="mt-5 grid grid-cols-2 gap-3"><ResidentStat value="18" label="Parking sessions" /><ResidentStat value="42h" label="Total parked" /><ResidentStat value="3" label="Guest passes" /><ResidentStat value="0" label="Violations" /></div></article></section><h2 className="mt-8 text-lg font-semibold">Quick actions</h2><section className="mt-3 grid gap-3 sm:grid-cols-3"><Quick href="/resident/vehicles" icon={CarFront} title="Manage vehicles" text="View or register a vehicle" /><Quick href="/resident/guest-parking" icon={UserPlus} title="Invite a guest" text="Create a temporary pass" /><Quick href="/resident/vehicles/register" icon={Plus} title="Register vehicle" text="Add a new vehicle" /></section><section className="mt-8 grid gap-4 lg:grid-cols-2"><article className="panel p-5"><h2 className="panel-title">Recent activity</h2>{[['Entered garage','Today, 8:42 AM'],['Exited garage','Yesterday, 6:18 PM'],['Guest pass created','Aug 5, 2:04 PM']].map(([a,b])=><div key={a} className="flex items-center gap-3 border-b py-4 last:border-0"><span className="table-icon"><Clock3 /></span><div><p className="text-sm font-semibold">{a}</p><p className="text-xs text-muted-foreground">{b}</p></div></div>)}</article><article className="panel p-5"><h2 className="panel-title">Parking reminders</h2><div className="mt-5 rounded-xl bg-muted p-4"><div className="flex gap-3"><CalendarClock className="size-5 shrink-0 text-primary" /><div><p className="text-sm font-semibold">Guest pass expires today</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Sarah Miller’s pass expires at 8:00 PM.</p><Link href="/resident/guest-parking" className="mt-3 inline-block text-xs font-semibold text-primary">Manage pass →</Link></div></div></div></article></section></ResidentShell>
}
function ResidentStat({value,label}:{value:string;label:string}){return <div className="rounded-xl bg-muted/60 p-4"><p className="text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>}
function Quick({href,icon:Icon,title,text}:{href:string;icon:typeof CarFront;title:string;text:string}){return <Link href={href} className="panel group flex items-center gap-4 p-5 transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><span className="stat-icon stat-primary"><Icon /></span><div><p className="font-semibold group-hover:text-primary">{title}</p><p className="text-xs text-muted-foreground">{text}</p></div></Link>}

export function MyVehiclesPage() {
  const [cars,setCars]=useState([{plate:'8ABC123',model:'Tesla Model 3',color:'Midnight Silver',primary:true,status:'Parked',space:'A-024'},{plate:'6PARK42',model:'Volvo XC40',color:'Crystal White',primary:false,status:'Away',space:'A-024'}]); const [selected,setSelected]=useState(cars[0]); const [open,setOpen]=useState(false)
  return <ResidentShell><PageHeader title="My vehicles" description="Manage the vehicles connected to your resident parking account." action={<Link href="/resident/vehicles/register" className="button-primary"><Plus />Register vehicle</Link>} /><section className="grid gap-4 lg:grid-cols-2">{cars.map(car=><article key={car.plate} className="panel overflow-hidden"><div className="flex items-start justify-between p-5"><div className="flex gap-4"><span className="stat-icon stat-primary"><CarFront /></span><div><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-lg font-bold">{car.plate}</p>{car.primary&&<Status tone="info">Primary</Status>}</div><p className="mt-1 text-sm font-medium">{car.model}</p><p className="text-xs text-muted-foreground">{car.color}</p></div></div><button className="icon-button" onClick={()=>{setSelected(car);setOpen(true)}}><MoreHorizontal/></button></div><div className="grid grid-cols-2 border-t bg-muted/30"><div className="p-4"><p className="text-xs text-muted-foreground">Status</p><Status tone={car.status==='Parked'?'success':'neutral'}>{car.status}</Status></div><div className="border-l p-4"><p className="text-xs text-muted-foreground">Assigned space</p><p className="mt-1 font-mono font-semibold">{car.space}</p></div></div></article>)}</section><Modal open={open} onClose={()=>setOpen(false)} title={selected.plate}><div className="flex flex-col gap-3"><button className="button-secondary justify-start"><Edit3/>Edit vehicle</button><button className="button-secondary justify-start" onClick={()=>setCars(cars.map(c=>({...c,primary:c.plate===selected.plate})))}><Check/>Set as primary</button><button className="button-secondary justify-start text-destructive" onClick={()=>{setCars(cars.filter(c=>c.plate!==selected.plate));setOpen(false)}}><Trash2/>Remove vehicle</button></div></Modal></ResidentShell>
}

export function RegisterVehiclePage(){
  const router=useRouter(); const [step,setStep]=useState(1); const [plate,setPlate]=useState(''); const [details,setDetails]=useState({make:'',model:'',color:''});
  function next(e:FormEvent){e.preventDefault(); if(step<3)setStep(step+1); else setStep(4)}
  return <ResidentShell><div className="mx-auto max-w-2xl"><Link href="/resident/vehicles" className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground"><ChevronLeft className="size-4"/>Back to vehicles</Link><PageHeader title="Register a vehicle" description="Add a vehicle to your resident parking account." /><div className="mb-6 flex items-center gap-2">{[1,2,3].map(n=><div key={n} className="flex flex-1 items-center gap-2"><span className={`step-dot ${step>=n?'step-dot-active':''}`}>{step>n?<Check/>:n}</span>{n<3&&<span className={`h-0.5 flex-1 ${step>n?'bg-primary':'bg-border'}`}/>}</div>)}</div><section className="panel p-6">{step===4?<div className="py-10 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-success/10 text-success"><Check className="size-8"/></span><h2 className="mt-5 text-2xl font-bold">Vehicle submitted</h2><p className="mt-2 text-sm text-muted-foreground">Your registration is pending administrator approval.</p><button className="button-primary mt-6" onClick={()=>router.push('/resident/vehicles')}>Return to my vehicles</button></div>:<form onSubmit={next} className="flex flex-col gap-5"><div><p className="section-kicker">Step {step} of 3</p><h2 className="mt-2 text-xl font-semibold">{step===1?'Vehicle identity':step===2?'Vehicle details':'Review registration'}</h2></div>{step===1&&<label className="field"><span>License plate</span><input value={plate} onChange={e=>setPlate(e.target.value.toUpperCase())} placeholder="e.g. 8ABC123" required/></label>}{step===2&&<><div className="grid gap-4 sm:grid-cols-2"><label className="field"><span>Make</span><input value={details.make} onChange={e=>setDetails({...details,make:e.target.value})} placeholder="Tesla" required/></label><label className="field"><span>Model</span><input value={details.model} onChange={e=>setDetails({...details,model:e.target.value})} placeholder="Model 3" required/></label></div><label className="field"><span>Color</span><input value={details.color} onChange={e=>setDetails({...details,color:e.target.value})} placeholder="Midnight Silver" required/></label></>}{step===3&&<div className="rounded-xl bg-muted p-5"><Review label="License plate" value={plate}/><Review label="Vehicle" value={`${details.make} ${details.model}`}/><Review label="Color" value={details.color}/><Review label="Assigned unit" value="A-1204"/></div>}<div className="mt-2 flex justify-between"><button type="button" className="button-secondary" onClick={()=>setStep(Math.max(1,step-1))} disabled={step===1}>Back</button><button className="button-primary">{step===3?'Submit registration':'Continue'}</button></div></form>}</section></div></ResidentShell>
}
function Review({label,value}:{label:string;value:string}){return <div className="flex justify-between border-b py-3 last:border-0"><span className="text-sm text-muted-foreground">{label}</span><strong className="text-sm">{value}</strong></div>}

export function GuestParkingPage(){
  const [tab,setTab]=useState('Active'); const [open,setOpen]=useState(false); const [passes,setPasses]=useState([{name:'Sarah Miller',plate:'7GUEST1',window:'Today · 2:00 PM–8:00 PM',status:'Active',code:'GP-2094'},{name:'Daniel Lee',plate:'4VISIT8',window:'Aug 10 · 9:00 AM–4:00 PM',status:'Upcoming',code:'GP-2112'}]);
  function create(e:FormEvent){e.preventDefault();setPasses([...passes,{name:'New Guest',plate:'PENDING',window:'Tomorrow · 9:00 AM–5:00 PM',status:'Upcoming',code:`GP-${2200+passes.length}`}]);setOpen(false)}
  const shown=passes.filter(p=>tab==='History'?false:p.status===tab)
  return <ResidentShell><PageHeader title="Guest parking" description="Create and manage temporary parking access for your visitors." action={<button className="button-primary" onClick={()=>setOpen(true)}><Plus/>Create guest pass</button>} /><section className="mb-4 grid gap-4 sm:grid-cols-3"><ResidentStat value="1" label="Active pass"/><ResidentStat value="3" label="Passes this month"/><ResidentStat value="22h" label="Guest parking time"/></section><div className="panel overflow-hidden"><div className="flex gap-2 border-b p-4">{['Active','Upcoming','History'].map(t=><button key={t} onClick={()=>setTab(t)} className={`filter-chip ${tab===t?'filter-chip-active':''}`}>{t}</button>)}</div><div className="grid gap-4 p-4 lg:grid-cols-2">{shown.map(p=><article key={p.code} className="rounded-xl border p-5"><div className="flex items-start justify-between"><div><Status tone={p.status==='Active'?'success':'info'}>{p.status}</Status><h3 className="mt-3 text-lg font-semibold">{p.name}</h3><p className="font-mono text-sm text-muted-foreground">{p.plate}</p></div><div className="qr-mark" aria-label="QR code"><QrCode/></div></div><div className="mt-5 rounded-xl bg-muted p-3 text-sm"><p className="flex items-center gap-2"><Clock3 className="size-4 text-primary"/>{p.window}</p><p className="mt-2 flex items-center gap-2"><MapPin className="size-4 text-primary"/>Guest Zone · Level G</p></div><div className="mt-4 flex gap-2"><button className="button-secondary flex-1 justify-center" onClick={()=>navigator.clipboard?.writeText(p.code)}><Copy/>Copy</button><button className="button-secondary flex-1 justify-center"><Share2/>Share</button><button className="icon-button text-destructive" onClick={()=>setPasses(passes.filter(x=>x.code!==p.code))}><Trash2/></button></div></article>)}{!shown.length&&<div className="col-span-full py-14 text-center"><Users className="mx-auto size-8 text-muted-foreground"/><p className="mt-3 font-semibold">No {tab.toLowerCase()} guest passes</p></div>}</div></div><Modal open={open} onClose={()=>setOpen(false)} title="Create guest pass"><form onSubmit={create} className="flex flex-col gap-4"><label className="field"><span>Guest name</span><input placeholder="Full name" required/></label><label className="field"><span>License plate</span><input placeholder="License plate" required/></label><div className="grid gap-4 sm:grid-cols-2"><label className="field"><span>Arrival</span><input type="datetime-local" required/></label><label className="field"><span>Departure</span><input type="datetime-local" required/></label></div><label className="field"><span>Notes</span><textarea rows={3} placeholder="Optional instructions"/></label><button className="button-primary justify-center"><KeyRound/>Create pass</button></form></Modal></ResidentShell>
}
